/**
 * QGIS layer style (.qml) generation for ACMA RRL query results.
 *
 * Companion to geojson.ts / kml.ts: those carry the data, this carries the
 * presentation. QGIS applies a .qml automatically when it sits beside the data
 * file with the same basename, so the same result can be exported twice and the
 * layer arrives styled — see docs/geospatial-export.md.
 *
 * The map tip is the part worth generating. It is tedious to hand-write, has to
 * name every field exactly, and is the reason attributes appear to be "missing"
 * in QGIS: the data is in the attribute table, but nothing shows on hover until a
 * tip exists and View > Show Map Tips is on.
 *
 * TESTABILITY, stated plainly: there is no QGIS in CI, so nothing here proves the
 * style RENDERS. What the tests do cover is every failure mode that silently
 * produces a broken or empty style — malformed XML, an unescaped metacharacter, a
 * field name that breaks expression syntax, or a tip referencing a column the data
 * does not have. QGIS schema drift across versions is a real residual risk.
 */

export interface QmlOptions {
    /** Column to label features with. Defaults to NAME, else the first string column. */
    labelField?: string;
    /** Columns to show in the map tip. Defaults to every attribute column. */
    fields?: string[];
}

/** Written against the QGIS 3.28 schema; 3.x reads it, later majors may drift. */
const QGIS_VERSION = '3.28.0';

export function generateQml(
    columns: string[],
    rows: unknown[][],
    options: QmlOptions = {},
): string {
    const lCols = columns.map(c => c.toLowerCase());
    const geometryCols = new Set(
        ['latitude', 'longitude', 'geometry']
            .map(c => lCols.indexOf(c))
            .filter(i => i >= 0),
    );

    const attributes = columns.filter((c, i) => !geometryCols.has(i) && isExpressionSafe(c));
    const tipFields = options.fields
        ? options.fields.filter(f => attributes.includes(f))
        : attributes;

    const labelField = chooseLabelField(columns, rows, geometryCols, options.labelField);

    return `<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="${QGIS_VERSION}" styleCategories="Symbology|Labeling|MapTips">
  <!--
    Generated by the ACMA RRL MCP server (export_qml).

    Save this beside the data file with the SAME BASENAME and QGIS applies it on
    load, e.g. stations.geojson + stations.qml. To drop it, delete the file or use
    Layer Properties > Style > Restore Default.

    Map tips are a QGIS-wide toggle, not a layer setting: turn them on once with
    View > Show Map Tips, or the tip will never appear however this file is written.
  -->
${renderer()}
${labelField ? labeling(labelField) : '  <!-- no labelling: no column suitable as a label -->'}
  <mapTip>${xmlEscape(mapTipHtml(tipFields))}</mapTip>
</qgis>
`;
}

/**
 * A field name is interpolated into a QGIS expression as [% "NAME" %]. A double
 * quote would terminate it early and produce an expression that fails to parse, so
 * such a column is left out rather than shipped broken.
 */
function isExpressionSafe(column: string): boolean {
    return column.length > 0 && !column.includes('"') && !column.includes('%');
}

function chooseLabelField(
    columns: string[],
    rows: unknown[][],
    geometryCols: Set<number>,
    explicit?: string,
): string | null {
    if (explicit && columns.includes(explicit) && isExpressionSafe(explicit)) return explicit;

    const nameIdx = columns.map(c => c.toLowerCase()).indexOf('name');
    if (nameIdx >= 0 && isExpressionSafe(columns[nameIdx]!)) return columns[nameIdx]!;

    // Otherwise the first column that actually holds text — a numeric id makes a
    // poor label.
    for (let i = 0; i < columns.length; i++) {
        if (geometryCols.has(i) || !isExpressionSafe(columns[i]!)) continue;
        const sample = rows.find(r => r[i] !== null && r[i] !== undefined && r[i] !== '');
        if (sample && typeof sample[i] === 'string') return columns[i]!;
    }
    return null;
}

function renderer(): string {
    return `  <renderer-v2 type="singleSymbol" forceraster="0" symbollevels="0" enableorderby="0">
    <symbols>
      <symbol type="marker" name="0" alpha="1" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleMarker" enabled="1" pass="0" locked="0">
          <Option type="Map">
            <Option name="name" type="QString" value="circle"/>
            <Option name="color" type="QString" value="230,74,25,255"/>
            <Option name="outline_color" type="QString" value="255,255,255,255"/>
            <Option name="outline_width" type="QString" value="0.3"/>
            <Option name="outline_width_unit" type="QString" value="MM"/>
            <Option name="size" type="QString" value="2.6"/>
            <Option name="size_unit" type="QString" value="MM"/>
            <Option name="angle" type="QString" value="0"/>
            <Option name="offset" type="QString" value="0,0"/>
            <Option name="offset_unit" type="QString" value="MM"/>
            <Option name="scale_method" type="QString" value="diameter"/>
            <Option name="horizontal_anchor_point" type="QString" value="1"/>
            <Option name="vertical_anchor_point" type="QString" value="1"/>
          </Option>
        </layer>
      </symbol>
    </symbols>
  </renderer-v2>`;
}

function labeling(field: string): string {
    return `  <labeling type="simple">
    <settings calloutType="simple">
      <text-style fontFamily="Sans Serif" fontSize="8" fontWeight="50" fontItalic="0"
                  textColor="40,40,40,255" fieldName="${xmlEscape(field)}" isExpression="0"
                  textOpacity="1" multilineHeight="1" allowHtml="0">
        <text-buffer bufferDraw="1" bufferSize="1" bufferSizeUnits="MM"
                     bufferColor="255,255,255,230" bufferOpacity="1" bufferJoinStyle="128"/>
      </text-style>
      <text-format placeDirectionSymbol="0" multilineAlign="0" wrapChar=""/>
      <placement placement="6" dist="1.5" distUnits="MM" priority="5"
                 overlapHandling="PreventOverlap" quadOffset="4"/>
      <rendering scaleVisibility="1" scaleMin="0" scaleMax="1500000"
                 displayAll="0" labelPerPart="0"/>
    </settings>
  </labeling>`;
}

/** The tip body, as HTML with [% "FIELD" %] expressions QGIS evaluates per feature. */
function mapTipHtml(fields: string[]): string {
    if (fields.length === 0) return '<i>no attributes</i>';

    const [first, ...rest] = fields;
    const heading = `<b style="font-size:12px">[% "${first}" %]</b>`;
    const body = rest
        .map(f => `<tr><td style="padding:1px 6px 1px 0; color:#555; white-space:nowrap">`
                + `${htmlEscape(f)}</td><td style="padding:1px 0">[% "${f}" %]</td></tr>`)
        .join('\n');

    return `<div style="font-family:sans-serif; font-size:11px; max-width:420px">
${heading}
<table>
${body}
</table>
</div>`;
}

/** Escaping for XML element text and attribute values. */
function xmlEscape(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

/** Escaping for a column name shown as literal text inside the tip's HTML. */
function htmlEscape(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
